name: 'Simple Replace Action'
description: 'Replaces substrings in files. Useful to enrich configs with previous steps artifacts.'
author: LB
branding:
  icon: 'repeat'  
  color: 'green'
inputs:
  files:
    description: 'Files with the PLACEHOLDER to be replaced in them. Separated by comma, semicolon or newline.'
    required: true
  replacements:
    description: 'Variable pairs PLACEHOLDER=value. Separated by comma, semicolon or newline.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
